# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Andrii Omelianovych
description:      'Description'
url:              https://vedmid.github.io
baseurl:          


paginate:         5

github:
  repo:           https://github.com/vedmid/vedmid.github.io

plugins: [jekyll-gist, jekyll-archives, jekyll-paginate]
